# Generated by Django 3.1.14 on 2023-06-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230615_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('excluido', 'Excluído'), ('emprestado', 'Emprestado'), ('reparo', 'Em Reparo'), ('reservado', 'Reservado')], default='disponivel', max_length=20),
        ),
    ]
