# Generated by Django 3.1.14 on 2023-06-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_equipamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/equipments/'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('excluido', 'Excluído'), ('emprestado', 'Emprestado'), ('reparo', 'Em Reparo'), ('reservado', 'Reservado')], default='Disponível', max_length=20),
        ),
    ]
