# Generated by Django 3.1.14 on 2023-06-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230616_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.CharField(choices=[('filmadoras', 'filmadoras'), ('microfones', 'microfones'), ('kits', 'kits')], default='Disponível', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='myproject/core/static/img/equipments/'),
        ),
    ]
